@startuml 用户状态图

left to right direction
hide empty description

[*] --> 打开软件
打开软件 --> 进入设备 : 点击文件夹
打开软件 : 进入软件主页
进入设备 : 可能是本地设备也可能是网络设备
进入设备 --> 打开软件 : 返回主页
进入设备 --> 进入设备 : 返回上一级
进入设备 --> 进入设备 : 点击文件夹
进入设备 -down-> 对应文件阅读器 : 点击文件
对应文件阅读器 : 多媒体文件阅读器，不同的文件类型不同路由
对应文件阅读器 --> 进入设备 : 返回上一级

打开软件 --> 设置页面 : 点击设置
打开软件 --> 导入网络设备 : 点击导入按钮
导入网络设备 : 连接保存用户输入的网络设备（webdav等）
设置页面 --> 设置页面 : 更改设置
设置页面 --> 打开软件 : 点击返回
设置页面 --> 打开软件 : 清除缓存,重载

导入网络设备 --> 打开软件 : 点击返回
导入网络设备 --> 导入网络设备 : 输入网络设备配置文件

打开软件 -[hidden]-> 对应文件阅读器

@enduml