@startmindmap "系统功能模块图"

* koko_app
** 文件管理
*** 文件浏览
*** 文件基础操作
**** 文件重命名
**** 文件删除
**** 文件移动
**** 文件复制
*** 文件打开
*** 文件排序
*** 文件多选
*** 导入网络源

** 多媒体阅读
*** 视频
*** 音频
*** 图片
*** EPUB
*** ...

** 辅助功能
*** 基础设置
**** 主题设置
**** ...
*** 页面设置
**** 页面模式设置
**** ...
*** EPUB设置
**** 预缓存页数
**** ...
*** 缓存设置
**** 本地缓存
**** ...

@endmindmap