@startuml 系统层级架构图

node node[
  UI渲染层
  ....
  负责用户界面的展示和交互，包括UI组件、路由页面等。
  ===
  数据模型层
  ....
  整个系统的数据源，包括与数据接口进行通信的实体、辅助
  其他层的枚举类、以及软件的状态模型。
  ===
  数据接口层
  ....
  数据源接口，软件通过数据源接口获取所需要的数据，是数
  据通信的协议，通过实现代码中定义的数据接口让软件与外
  部数据源（本地文件系统、webdav服务器）相连，让软件
  与外部数据源通信并处理。
  ===
  状态管理层
  ....
  对于全局的配置文件等进行状态管理，保证跨组件、跨路由
  的通信和数据共享以及软件状态改变时对各组件的即时通知。
]

@enduml