@startuml 网络图片缩略缓存流程图

start
:用户请求网络图片;
if (图片存在于内存缓存?) then (是)
  :直接返回内存缓存图片;
  stop
else (否)
  if (图片存在于硬盘缓存?) then (是)
    :加载硬盘缓存图片到内存;
    :返回硬盘缓存图片;
    stop
  else (否)
    :向网络请求图片;
    :对图片进行缩略处理;
    :将缩略图片存入内存缓存;
    :将缩略图片存入硬盘缓存;
    :返回缩略图片;
    stop
  endif
endif

@enduml